### ISSUE TITLE
Provide PWA version

### ISSUE THREAD

**Issue by geiseri** [open-source-labs/PreVue#98]
I am on a chomebook and this looks very handy to talk with clients about designs.  How hard would it be to have this as a PWA?  I can't see any big stuff electron specific save for the export.  Could there be a html5 only version that just created the `.json` file and the desktop would create the code output?

**Comment by hubelin** [comment]
Hey, a team actually forked our project and made some cool updates, I'd recommend checking out their project. I believe their site also has a demo that might be what you're interested in.

https://www.overvue.io/
https://github.com/open-source-labs/OverVue
